name: Check PR

on:
  pull_request:
    branches:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: 'r28b'
        add-to-path: true

    - name: Set up environment variables
      run: |
        echo "ANDROID_NDK=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV


    - name: Get version from tag
      id: get_version
      run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Build libtorrent for all architectures
      id: build_libtorrent
      run: |
        chmod +x build.sh
        ./build.sh || {
          echo "Build failed with exit code $?"
          exit 1
        }

